---
# Packages every server gets
base_packages:
  - curl
  - wget
  - vim
  - htop
  - git
  - unzip
  - ca-certificates
  - bash-completion

# Timezone for the server
base_timezone: "Europe/Belgrade"
